# Generated by Django 2.2.7 on 2021-09-22 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo_responsable', '0001_initial'),
        ('jefaturas', '0001_initial'),
        ('auditoria', '0001_initial'),
        ('estados_hallazgo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ges_Hallazgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_hallazgo', models.IntegerField()),
                ('proceso', models.CharField(blank=True, max_length=200, null=True)),
                ('naturaleza', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion_hallazgo', models.CharField(max_length=2500)),
                ('criterios', models.CharField(blank=True, max_length=1500, null=True)),
                ('causas', models.CharField(blank=True, max_length=1000, null=True)),
                ('efectos', models.CharField(blank=True, max_length=1000, null=True)),
                ('sumario', models.CharField(blank=True, max_length=150, null=True)),
                ('recomendacion', models.CharField(blank=True, max_length=1500, null=True)),
                ('plazo', models.DateTimeField(blank=True, null=True)),
                ('opinion', models.CharField(blank=True, max_length=150, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
                ('cargo_responsable_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cargo_responsable.Ges_Cargo_Hallazgo')),
                ('enc_gestion_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_auditoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auditoria.Ges_auditoria')),
                ('id_estadoshallazgo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='estados_hallazgo.Glo_EstadosHallazgo')),
                ('jefatura_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jefaturas.Ges_Jefatura')),
            ],
        ),
    ]
