# Generated by Django 2.2.7 on 2021-11-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallazgos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ges_hallazgo',
            name='numero_hallazgo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
