# Generated by Django 2.2.7 on 2021-09-22 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hallazgos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo_responsable', '0001_initial'),
        ('estado_compromiso', '0001_initial'),
        ('jefaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ges_Compromisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_compromiso', models.CharField(blank=True, max_length=1500, null=True)),
                ('medio_verificacion', models.CharField(blank=True, max_length=1000, null=True)),
                ('plazo_implementacion', models.DateTimeField(blank=True, null=True)),
                ('comentario_compromiso', models.CharField(blank=True, max_length=1000, null=True)),
                ('comentario_auditor', models.CharField(blank=True, max_length=1500, null=True)),
                ('cargo_responsable_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cargo_responsable.Ges_Cargo_Hallazgo')),
                ('estado_compromiso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='estado_compromiso.Glo_Estado_Compromiso')),
                ('hallazgo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hallazgos.Ges_Hallazgo')),
                ('responsable_hallazgo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jefaturas.Ges_Jefatura')),
            ],
        ),
        migrations.CreateModel(
            name='Ges_Observaciones_Compromiso_Enc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_Observacion', models.CharField(blank=True, max_length=1500, null=True)),
                ('fecha_observacion', models.DateTimeField(blank=True, null=True)),
                ('visto', models.IntegerField(blank=True, null=True)),
                ('compromiso_observacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='compromisos.Ges_Compromisos')),
                ('usuario_observacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
