# Generated by Django 2.2.7 on 2021-09-22 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado_auditoria', '0001_initial'),
        ('jefaturas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ges_auditoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_auditoria', models.CharField(max_length=14)),
                ('anio_auditoria', models.IntegerField()),
                ('descripcion_auditoria', models.CharField(max_length=250)),
                ('alcance_auditoria', models.CharField(max_length=250)),
                ('fecha_inicio_auditoria', models.DateField()),
                ('fecha_termino_auditoria', models.DateField(blank=True, null=True)),
                ('estado_auditoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estado_auditoria.Glo_EstadoAuditoria')),
                ('jefatura_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jefaturas.Ges_Jefatura')),
                ('tipo_auditoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estado_auditoria.Glo_autoria_tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Glo_autoria_auditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_auditoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auditoria.Ges_auditoria')),
            ],
        ),
    ]
